### ISSUE TITLE
minor error at waybar.theme

### ISSUE THREAD

**Issue by kRHYME7** [rishav12s/Paranoid-Sweet#1]
# launching of waybar got extra chars
https://github.com/rishav12s/Paranoid-Sweet/blob/ee639b18631580e8b3f4d3d4a2425be80fbf36aa/Configs/.config/hyde/themes/Paranoid%20Sweet/waybar.theme#L1C1-L1C56

# did not used hyprcursor hence having inconsistent cursors on scaled monitors 

So you can run this lame script to the cursor directory to generate hyprcursors
` Hyde --dev convert_cursor ~/.icons/Sweet-cursors`
![image](https://github.com/user-attachments/assets/116e4f57-250f-4d24-96b5-3bfd46228d1f)

**Comment by rishav12s** [comment]
@kRHYME7 waybar fixed could you explain the cursor issue 

I think they were converted to hyprcursor format 
got the sweet hyprcursor from a aur package

**Comment by kRHYME7** [comment]
can you ls the contents of that dir?

**Comment by kRHYME7** [comment]
The arcs ships the hyprcursors already. Will close this now

**Comment by rishav12s** [comment]
@kRHYME7  is it ok for a pr to hyde-gallery ? 

i will update readme for it in the meantime 
if any more changes required you could tell 👍

**Comment by kRHYME7** [comment]
Yes do a PR. 

` Hyde theme patch "Paranoid Sweet" https://github.com/rishav12s/Paranoid-Sweet `
